# Generated by Django 5.1.1 on 2025-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Dart', 'Dart'), ('Objective-C', 'Objective-C'), ('TypeScript', 'TypeScript'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('Perl', 'Perl'), ('Scala', 'Scala'), ('Haskell', 'Haskell'), ('Elixir', 'Elixir'), ('Erlang', 'Erlang'), ('Lua', 'Lua'), ('F#', 'F#'), ('Bash', 'Bash'), ('PowerShell', 'PowerShell'), ('Shell Scripting', 'Shell Scripting'), ('R', 'R'), ('MATLAB', 'MATLAB'), ('Julia', 'Julia'), ('COBOL', 'COBOL'), ('Fortran', 'Fortran'), ('Lisp', 'Lisp'), ('Prolog', 'Prolog'), ('Groovy', 'Groovy'), ('VB.NET', 'VB.NET'), ('Assembly', 'Assembly'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SASS/SCSS', 'SASS/SCSS'), ('Tailwind CSS', 'Tailwind CSS'), ('Bootstrap', 'Bootstrap'), ('React', 'React'), ('Next.js', 'Next.js'), ('Vue.js', 'Vue.js'), ('Nuxt.js', 'Nuxt.js'), ('Angular', 'Angular'), ('Svelte', 'Svelte'), ('Ember.js', 'Ember.js'), ('jQuery', 'jQuery'), ('Three.js', 'Three.js'), ('Django', 'Django'), ('Flask', 'Flask'), ('FastAPI', 'FastAPI'), ('Express.js', 'Express.js'), ('NestJS', 'NestJS'), ('Spring Boot', 'Spring Boot'), ('ASP.NET Core', 'ASP.NET Core'), ('Ruby on Rails', 'Ruby on Rails'), ('Laravel', 'Laravel'), ('Symfony', 'Symfony'), ('CodeIgniter', 'CodeIgniter'), ('Phoenix', 'Phoenix'), ('Golang Gin', 'Golang Gin'), ('Fiber', 'Fiber'), ('SQL', 'SQL'), ('NoSQL', 'NoSQL'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('SQLite', 'SQLite'), ('MongoDB', 'MongoDB'), ('Cassandra', 'Cassandra'), ('Redis', 'Redis'), ('Firebase', 'Firebase'), ('DynamoDB', 'DynamoDB'), ('GraphQL', 'GraphQL'), ('Supabase', 'Supabase'), ('ElasticSearch', 'ElasticSearch'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Terraform', 'Terraform'), ('Ansible', 'Ansible'), ('CI/CD', 'CI/CD'), ('GitHub Actions', 'GitHub Actions'), ('Jenkins', 'Jenkins'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('Google Cloud', 'Google Cloud'), ('IBM Cloud', 'IBM Cloud'), ('OpenShift', 'OpenShift'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Big Data', 'Big Data'), ('Pandas', 'Pandas'), ('NumPy', 'NumPy'), ('SciPy', 'SciPy'), ('Matplotlib', 'Matplotlib'), ('Seaborn', 'Seaborn'), ('TensorFlow', 'TensorFlow'), ('PyTorch', 'PyTorch'), ('Keras', 'Keras'), ('OpenCV', 'OpenCV'), ('Cybersecurity', 'Cybersecurity'), ('Penetration Testing', 'Penetration Testing'), ('Ethical Hacking', 'Ethical Hacking'), ('Cryptography', 'Cryptography'), ('SIEM', 'SIEM'), ('SOC', 'SOC'), ('Network Security', 'Network Security'), ('Forensics', 'Forensics'), ('Game Development', 'Game Development'), ('Unity', 'Unity'), ('Unreal Engine', 'Unreal Engine'), ('Godot', 'Godot'), ('Cocos2d', 'Cocos2d'), ('AR/VR', 'AR/VR'), ('Blender', 'Blender'), ('UI/UX Design', 'UI/UX Design'), ('Figma', 'Figma'), ('Adobe XD', 'Adobe XD'), ('Sketch', 'Sketch'), ('InVision', 'InVision'), ('Balsamiq', 'Balsamiq'), ('Blockchain', 'Blockchain'), ('Smart Contracts', 'Smart Contracts'), ('IoT', 'IoT'), ('Embedded Systems', 'Embedded Systems'), ('Networking', 'Networking'), ('Robotics', 'Robotics'), ('Quantum Computing', 'Quantum Computing')], max_length=64, null=True, unique=True, verbose_name='Навички')),
            ],
            options={
                'verbose_name': 'Навичка',
                'verbose_name_plural': 'Навички',
            },
        ),
    ]
