# Generated by Django 5.1.1 on 2025-02-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=64, null=True, unique=True, verbose_name='Формат роботи')),
            ],
            options={
                'verbose_name': 'Формат роботи',
                'verbose_name_plural': 'Формати роботи',
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Dart', 'Dart'), ('Objective-C', 'Objective-C'), ('TypeScript', 'TypeScript'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('Perl', 'Perl'), ('Scala', 'Scala'), ('Haskell', 'Haskell'), ('Elixir', 'Elixir'), ('Erlang', 'Erlang'), ('Lua', 'Lua'), ('F#', 'F#'), ('Bash', 'Bash'), ('PowerShell', 'PowerShell'), ('Shell Scripting', 'Shell Scripting'), ('R', 'R'), ('MATLAB', 'MATLAB'), ('Julia', 'Julia'), ('COBOL', 'COBOL'), ('Fortran', 'Fortran'), ('Lisp', 'Lisp'), ('Prolog', 'Prolog'), ('Groovy', 'Groovy'), ('VB.NET', 'VB.NET'), ('Assembly', 'Assembly'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SASS/SCSS', 'SASS/SCSS'), ('Tailwind CSS', 'Tailwind CSS'), ('Bootstrap', 'Bootstrap'), ('React', 'React'), ('Next.js', 'Next.js'), ('Vue.js', 'Vue.js'), ('Nuxt.js', 'Nuxt.js'), ('Angular', 'Angular'), ('Svelte', 'Svelte'), ('Ember.js', 'Ember.js'), ('jQuery', 'jQuery'), ('Three.js', 'Three.js'), ('Gatsby', 'Gatsby'), ('Grunt', 'Grunt'), ('Parcel', 'Parcel'), ('Pug', 'Pug'), ('Django', 'Django'), ('Flask', 'Flask'), ('FastAPI', 'FastAPI'), ('Express.js', 'Express.js'), ('NestJS', 'NestJS'), ('Spring Boot', 'Spring Boot'), ('ASP.NET Core', 'ASP.NET Core'), ('Ruby on Rails', 'Ruby on Rails'), ('Laravel', 'Laravel'), ('Symfony', 'Symfony'), ('CodeIgniter', 'CodeIgniter'), ('Phoenix', 'Phoenix'), ('Golang Gin', 'Golang Gin'), ('Fiber', 'Fiber'), ('Elixir Phoenix', 'Elixir Phoenix'), ('Sails.js', 'Sails.js'), ('Koa.js', 'Koa.js'), ('SQL', 'SQL'), ('NoSQL', 'NoSQL'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('SQLite', 'SQLite'), ('MongoDB', 'MongoDB'), ('Cassandra', 'Cassandra'), ('Redis', 'Redis'), ('Firebase', 'Firebase'), ('DynamoDB', 'DynamoDB'), ('GraphQL', 'GraphQL'), ('Supabase', 'Supabase'), ('ElasticSearch', 'ElasticSearch'), ('CouchDB', 'CouchDB'), ('Neo4j', 'Neo4j'), ('Apache HBase', 'Apache HBase'), ('Amazon Redshift', 'Amazon Redshift'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Terraform', 'Terraform'), ('Ansible', 'Ansible'), ('CI/CD', 'CI/CD'), ('GitHub Actions', 'GitHub Actions'), ('Jenkins', 'Jenkins'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('Google Cloud', 'Google Cloud'), ('IBM Cloud', 'IBM Cloud'), ('OpenShift', 'OpenShift'), ('Pulumi', 'Pulumi'), ('CloudFormation', 'CloudFormation'), ('Vagrant', 'Vagrant'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Big Data', 'Big Data'), ('Pandas', 'Pandas'), ('NumPy', 'NumPy'), ('SciPy', 'SciPy'), ('Matplotlib', 'Matplotlib'), ('Seaborn', 'Seaborn'), ('TensorFlow', 'TensorFlow'), ('PyTorch', 'PyTorch'), ('Keras', 'Keras'), ('OpenCV', 'OpenCV'), ('Scikit-learn', 'Scikit-learn'), ('XGBoost', 'XGBoost'), ('LightGBM', 'LightGBM'), ('NLTK', 'NLTK'), ('spaCy', 'spaCy'), ('Hugging Face', 'Hugging Face'), ('Cybersecurity', 'Cybersecurity'), ('Penetration Testing', 'Penetration Testing'), ('Ethical Hacking', 'Ethical Hacking'), ('Cryptography', 'Cryptography'), ('SIEM', 'SIEM'), ('SOC', 'SOC'), ('Network Security', 'Network Security'), ('Forensics', 'Forensics'), ('Firewalls', 'Firewalls'), ('IDS/IPS', 'IDS/IPS'), ('DDoS Protection', 'DDoS Protection'), ('Reverse Engineering', 'Reverse Engineering'), ('Game Development', 'Game Development'), ('Unity', 'Unity'), ('Unreal Engine', 'Unreal Engine'), ('Godot', 'Godot'), ('Cocos2d', 'Cocos2d'), ('AR/VR', 'AR/VR'), ('Blender', 'Blender'), ('Game Design', 'Game Design'), ('C# (Unity)', 'C# (Unity)'), ('Java (Android Games)', 'Java (Android Games)'), ('UI/UX Design', 'UI/UX Design'), ('Figma', 'Figma'), ('Adobe XD', 'Adobe XD'), ('Sketch', 'Sketch'), ('InVision', 'InVision'), ('Balsamiq', 'Balsamiq'), ('Wireframing', 'Wireframing'), ('Prototyping', 'Prototyping'), ('User Research', 'User Research'), ('Blockchain', 'Blockchain'), ('Smart Contracts', 'Smart Contracts'), ('IoT', 'IoT'), ('Embedded Systems', 'Embedded Systems'), ('Networking', 'Networking'), ('Robotics', 'Robotics'), ('Quantum Computing', 'Quantum Computing'), ('AR/VR Development', 'AR/VR Development'), ('5G', '5G'), ('Edge Computing', 'Edge Computing'), ('Serverless Computing', 'Serverless Computing')], max_length=64, null=True, unique=True, verbose_name='Навички'),
        ),
    ]
