# Generated by Django 5.1.1 on 2025-02-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
