# Generated by Django 5.1.1 on 2025-02-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_jobemployerprofile_vacancy'),
        ('vacancy', '0002_vacancy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='users.jobemployerprofile', verbose_name='Профіль роботодавця'),
        ),
    ]
