# Generated by Django 5.1.1 on 2025-02-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancy_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансія', 'verbose_name_plural': 'Вакансії'},
        ),
    ]
