# Generated by Django 5.1.1 on 2025-02-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_jobformat_alter_skill_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='job_format',
            field=models.ManyToManyField(blank=True, related_name='users', to='common.jobformat', verbose_name='Формат роботи'),
        ),
    ]
