# Generated by Django 5.1.1 on 2025-02-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_jobformat_alter_skill_name'),
        ('users', '0002_jobseekerprofile_job_format'),
        ('vacancy', '0002_vacancy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobemployerprofile',
            name='vacancies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='vacancy.vacancy', verbose_name='Вакансії'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='seeker_profile', to='common.skill', verbose_name='Навички'),
        ),
    ]
