# Generated by Django 5.1.1 on 2025-02-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jobemployerprofile_vacancies_and_more'),
        ('vacancy', '0002_vacancy_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobemployerprofile',
            name='vacancies',
        ),
        migrations.AddField(
            model_name='jobemployerprofile',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='vacancy.vacancy', verbose_name='Вакансії'),
        ),
    ]
